### ISSUE TITLE
Fix Travis CI build failing

### ISSUE THREAD

**Issue by CJKinni** [CJKinni/cjk_math#1]
After making a change to a readme, and changing my Github username, a travis CI build seems to be failing.

**Comment by dvrkps** [comment]
Remove 'release' from https://github.com/dvrkps/cjkmath/blob/master/.travis.yml#L4

For current release use release number(1.7)

For covealls you must rename/update repo on coveralls site.

**Comment by CJKinni** [comment]
Thanks.  Fixed.
